# .github/workflows/build-and-deploy.yml
name: Build and Deploy NixOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install Nix
      uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          
    - name: Setup Cachix (optional - speeds up builds)
      uses: cachix/cachix-action@v12
      with:
        name: nix-community
        
    - name: Build NixOS system configuration
      run: |
        # Build the system closure
        nix build .#nixosConfigurations.droplet.config.system.build.toplevel \
          --print-build-logs \
          --out-link system-closure
          
        # Get the store path for deployment
        SYSTEM_PATH=$(readlink ./system-closure)
        echo "Built system: $SYSTEM_PATH"
        
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
        
    - name: Deploy to server
      if: github.ref == 'refs/heads/main'
      run: |
        # Get the store path
        SYSTEM_PATH=$(readlink ./system-closure)
        echo "Deploying system: $SYSTEM_PATH"
        
        echo "Copying closure to server..."
        if timeout 900 nix-copy-closure --to root@${{ secrets.SERVER_HOST }} $SYSTEM_PATH; then
          echo "Copy successful, activating configuration..."
          
          # Activate the new configuration with error handling
          ssh root@${{ secrets.SERVER_HOST }} "
            set -e
            echo 'Starting activation...'
            if timeout 300 $SYSTEM_PATH/bin/switch-to-configuration test; then
              echo 'Test activation successful, making permanent...'
              $SYSTEM_PATH/bin/switch-to-configuration switch
              echo 'Deployment completed successfully!'
            else
              echo 'Test activation failed or timed out'
              exit 1
            fi
          "
        else
          echo "ERROR: Failed to copy closure to server"
          exit 1
        fi
